# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/main ./cmd/server && make swag-gen"
bin = "tmp/main"
exclude_dir = ["assets", "tmp", "vendor", "docs"]
include_ext = ["go"]

[log]
time = true
