version: "3.8"
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hackathon
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Сервис для Adminer (администрирование PostgreSQL через веб-интерфейс)
  adminer:
    image: adminer
    ports:
      - "8081:8080"

  app:
    build: .
    volumes:
      - .:/app  # Монтируем исходный код
    ports:
      - "4242:4242"
    command: air
    depends_on:
      - postgres

volumes:
  postgres_data:
